version: '3.8'

services:

  web:
    build: ./project
    container_name: teste_topaz
    command: uvicorn app.main.main:app --reload --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
